import { jsPDF } from "jspdf";
import { format } from "date-fns";
import { Employee } from "@/types";

export type DocType = "offer-letter" | "confirmation-letter" | "increment-letter" | "promotion-letter" | "relieving-letter";

export const DOC_TYPE_LABELS: Record<DocType, string> = {
  "offer-letter": "Offer Letter",
  "confirmation-letter": "Confirmation Letter",
  "increment-letter": "Increment Letter",
  "promotion-letter": "Promotion Letter",
  "relieving-letter": "Relieving Letter",
};

function addHeader(doc: jsPDF, pageWidth: number, margin: number) {
  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, pageWidth, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("HRMS Enterprise Suite", margin, 18);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("admin@company.com  |  www.hrmsportal.com", margin, 25);
}

function addFooter(doc: jsPDF, pageWidth: number) {
  doc.setFillColor(99, 102, 241);
  doc.rect(0, doc.internal.pageSize.getHeight() - 12, pageWidth, 12, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.text("Confidential — This document is generated by HRMS Enterprise Suite", pageWidth / 2, doc.internal.pageSize.getHeight() - 4, { align: "center" });
}

function addSignatures(doc: jsPDF, margin: number, pageWidth: number, y: number) {
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("Authorised Signatory", margin, y);
  doc.text("HR Department", pageWidth - margin - 50, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("HRMS Enterprise Suite", margin, y);
  doc.text("Human Resources", pageWidth - margin - 50, y);
}

export function generateOfferLetterPDF(employee: Employee) {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 0;

  addHeader(doc, pageWidth, margin);

  y = 45;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("OFFER LETTER", pageWidth / 2, y, { align: "center" });

  y += 12;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Date: ${format(new Date(), "dd MMMM yyyy")}`, pageWidth - margin, y, { align: "right" });
  doc.text(`Ref: OL-${employee.employeeId}`, margin, y);

  y += 14;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.text(`Dear ${employee.firstName} ${employee.lastName},`, margin, y);

  y += 10;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const introText = `We are pleased to offer you the position of ${employee.designation} in our ${employee.department} department. This offer is contingent upon successful completion of our standard background verification process.`;
  const splitIntro = doc.splitTextToSize(introText, pageWidth - margin * 2);
  doc.text(splitIntro, margin, y);
  y += splitIntro.length * 6 + 8;

  const terms = [
    ["Position", employee.designation],
    ["Department", employee.department],
    ["Employment Type", employee.employmentType],
    ["Date of Joining", employee.joiningDate],
    ["Work Location", employee.workLocation || employee.officeLocation],
    ["Reporting Manager", employee.reportingManager],
    ["Shift Timing", employee.shiftTiming],
    ["Company Email", employee.companyEmail],
  ];

  doc.setFillColor(240, 240, 255);
  doc.rect(margin, y - 4, pageWidth - margin * 2, 10, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Employment Terms & Conditions", margin + 2, y + 3);
  y += 14;

  terms.forEach(([label, value], i) => {
    if (i % 2 === 0) {
      doc.setFillColor(250, 250, 252);
      doc.rect(margin, y - 4, pageWidth - margin * 2, 10, "F");
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text(`${label}:`, margin + 2, y + 2);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.text(String(value || "—"), margin + 55, y + 2);
    y += 10;
  });

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  const closing = "Please sign and return a copy of this letter to confirm your acceptance. We look forward to welcoming you to our team.";
  const splitClosing = doc.splitTextToSize(closing, pageWidth - margin * 2);
  doc.text(splitClosing, margin, y);
  y += splitClosing.length * 6 + 20;

  addSignatures(doc, margin, pageWidth, y);
  addFooter(doc, pageWidth);
  return doc;
}

export function generateConfirmationLetterPDF(employee: Employee) {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 0;

  addHeader(doc, pageWidth, margin);

  y = 45;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("CONFIRMATION LETTER", pageWidth / 2, y, { align: "center" });

  y += 12;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Date: ${format(new Date(), "dd MMMM yyyy")}`, pageWidth - margin, y, { align: "right" });
  doc.text(`Ref: CL-${employee.employeeId}`, margin, y);

  y += 14;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.text(`Dear ${employee.firstName} ${employee.lastName},`, margin, y);

  y += 10;
  doc.setFontSize(10);
  const body1 = `We are pleased to confirm your employment with HRMS Enterprise Suite as ${employee.designation} in the ${employee.department} department, effective from ${employee.joiningDate}.`;
  const split1 = doc.splitTextToSize(body1, pageWidth - margin * 2);
  doc.text(split1, margin, y);
  y += split1.length * 6 + 8;

  const body2 = `After a satisfactory review of your performance during the probation period, your services are hereby confirmed. All terms and conditions of employment as communicated in your original offer letter shall continue to apply.`;
  const split2 = doc.splitTextToSize(body2, pageWidth - margin * 2);
  doc.text(split2, margin, y);
  y += split2.length * 6 + 8;

  const terms = [
    ["Employee ID", employee.employeeId],
    ["Designation", employee.designation],
    ["Department", employee.department],
    ["Date of Joining", employee.joiningDate],
    ["Employment Type", employee.employmentType],
    ["Work Location", employee.workLocation || employee.officeLocation],
  ];

  doc.setFillColor(240, 240, 255);
  doc.rect(margin, y - 4, pageWidth - margin * 2, 10, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Confirmed Employment Details", margin + 2, y + 3);
  y += 14;

  terms.forEach(([label, value], i) => {
    if (i % 2 === 0) {
      doc.setFillColor(250, 250, 252);
      doc.rect(margin, y - 4, pageWidth - margin * 2, 10, "F");
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text(`${label}:`, margin + 2, y + 2);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.text(String(value || "—"), margin + 55, y + 2);
    y += 10;
  });

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  const closing = "We appreciate your dedication and look forward to your continued contributions to the organization. Congratulations on your confirmation!";
  const splitClosing = doc.splitTextToSize(closing, pageWidth - margin * 2);
  doc.text(splitClosing, margin, y);
  y += splitClosing.length * 6 + 20;

  addSignatures(doc, margin, pageWidth, y);
  addFooter(doc, pageWidth);
  return doc;
}

export function generateIncrementLetterPDF(employee: Employee) {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 0;

  addHeader(doc, pageWidth, margin);

  y = 45;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("INCREMENT LETTER", pageWidth / 2, y, { align: "center" });

  y += 12;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Date: ${format(new Date(), "dd MMMM yyyy")}`, pageWidth - margin, y, { align: "right" });
  doc.text(`Ref: IL-${employee.employeeId}`, margin, y);

  y += 14;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.text(`Dear ${employee.firstName} ${employee.lastName},`, margin, y);

  y += 10;
  doc.setFontSize(10);
  const body1 = `In recognition of your consistent performance and valuable contributions to the ${employee.department} department, we are pleased to inform you about a revision in your compensation package, effective from ${format(new Date(), "dd MMMM yyyy")}.`;
  const split1 = doc.splitTextToSize(body1, pageWidth - margin * 2);
  doc.text(split1, margin, y);
  y += split1.length * 6 + 8;

  const details = [
    ["Employee ID", employee.employeeId],
    ["Current Designation", employee.designation],
    ["Department", employee.department],
    ["Effective Date", format(new Date(), "dd MMMM yyyy")],
  ];

  doc.setFillColor(240, 240, 255);
  doc.rect(margin, y - 4, pageWidth - margin * 2, 10, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Increment Details", margin + 2, y + 3);
  y += 14;

  details.forEach(([label, value], i) => {
    if (i % 2 === 0) {
      doc.setFillColor(250, 250, 252);
      doc.rect(margin, y - 4, pageWidth - margin * 2, 10, "F");
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text(`${label}:`, margin + 2, y + 2);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.text(String(value || "—"), margin + 55, y + 2);
    y += 10;
  });

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  const body2 = "The revised compensation reflects our appreciation of your hard work and commitment. We encourage you to continue delivering excellent results.";
  const split2 = doc.splitTextToSize(body2, pageWidth - margin * 2);
  doc.text(split2, margin, y);
  y += split2.length * 6 + 8;

  const body3 = "All other terms and conditions of your employment remain unchanged. This letter is confidential and should not be shared with any third party.";
  const split3 = doc.splitTextToSize(body3, pageWidth - margin * 2);
  doc.text(split3, margin, y);
  y += split3.length * 6 + 20;

  addSignatures(doc, margin, pageWidth, y);
  addFooter(doc, pageWidth);
  return doc;
}

export function generatePromotionLetterPDF(employee: Employee) {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 0;

  addHeader(doc, pageWidth, margin);

  y = 45;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("PROMOTION LETTER", pageWidth / 2, y, { align: "center" });

  y += 12;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Date: ${format(new Date(), "dd MMMM yyyy")}`, pageWidth - margin, y, { align: "right" });
  doc.text(`Ref: PL-${employee.employeeId}`, margin, y);

  y += 14;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.text(`Dear ${employee.firstName} ${employee.lastName},`, margin, y);

  y += 10;
  doc.setFontSize(10);
  const body1 = `We are delighted to inform you that based on your exemplary performance and significant contributions, you have been promoted within the ${employee.department} department, effective ${format(new Date(), "dd MMMM yyyy")}.`;
  const split1 = doc.splitTextToSize(body1, pageWidth - margin * 2);
  doc.text(split1, margin, y);
  y += split1.length * 6 + 8;

  const details = [
    ["Employee ID", employee.employeeId],
    ["Current Designation", employee.designation],
    ["Department", employee.department],
    ["Effective Date", format(new Date(), "dd MMMM yyyy")],
    ["Reporting Manager", employee.reportingManager],
  ];

  doc.setFillColor(240, 240, 255);
  doc.rect(margin, y - 4, pageWidth - margin * 2, 10, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Promotion Details", margin + 2, y + 3);
  y += 14;

  details.forEach(([label, value], i) => {
    if (i % 2 === 0) {
      doc.setFillColor(250, 250, 252);
      doc.rect(margin, y - 4, pageWidth - margin * 2, 10, "F");
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text(`${label}:`, margin + 2, y + 2);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.text(String(value || "—"), margin + 55, y + 2);
    y += 10;
  });

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  const body2 = "This promotion is a testament to your dedication, leadership qualities, and the value you bring to the organization. We are confident you will continue to excel in your new role.";
  const split2 = doc.splitTextToSize(body2, pageWidth - margin * 2);
  doc.text(split2, margin, y);
  y += split2.length * 6 + 8;

  const body3 = "Your revised terms will be communicated separately. All other conditions of employment remain in effect. Congratulations!";
  const split3 = doc.splitTextToSize(body3, pageWidth - margin * 2);
  doc.text(split3, margin, y);
  y += split3.length * 6 + 20;

  addSignatures(doc, margin, pageWidth, y);
  addFooter(doc, pageWidth);
  return doc;
}

export function generateRelievingLetterPDF(employee: Employee) {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 0;

  addHeader(doc, pageWidth, margin);

  y = 45;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("RELIEVING LETTER", pageWidth / 2, y, { align: "center" });

  y += 12;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Date: ${format(new Date(), "dd MMMM yyyy")}`, pageWidth - margin, y, { align: "right" });
  doc.text(`Ref: RL-${employee.employeeId}`, margin, y);

  y += 14;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.text(`To Whomsoever It May Concern,`, margin, y);

  y += 10;
  doc.setFontSize(10);
  const body1 = `This is to certify that ${employee.firstName} ${employee.lastName} (Employee ID: ${employee.employeeId}) has been employed with HRMS Enterprise Suite as ${employee.designation} in the ${employee.department} Department from ${employee.joiningDate} to ${format(new Date(), "dd MMMM yyyy")}.`;
  const split1 = doc.splitTextToSize(body1, pageWidth - margin * 2);
  doc.text(split1, margin, y);
  y += split1.length * 6 + 8;

  const body2 = `${employee.firstName} has been relieved from ${employee.employmentType === "Full-time" ? "full-time" : employee.employmentType.toLowerCase()} employment effective ${format(new Date(), "dd MMMM yyyy")} as per mutual agreement. We appreciate the contributions made during the tenure.`;
  const split2 = doc.splitTextToSize(body2, pageWidth - margin * 2);
  doc.text(split2, margin, y);
  y += split2.length * 6 + 8;

  const body3 = `During the tenure, we found ${employee.firstName} to be sincere, hardworking and a team player. We wish ${employee.firstName} all the best in future endeavors.`;
  const split3 = doc.splitTextToSize(body3, pageWidth - margin * 2);
  doc.text(split3, margin, y);
  y += split3.length * 6 + 20;

  addSignatures(doc, margin, pageWidth, y);
  addFooter(doc, pageWidth);
  return doc;
}

export function generatePDF(employee: Employee, type: DocType) {
  switch (type) {
    case "offer-letter": return generateOfferLetterPDF(employee);
    case "confirmation-letter": return generateConfirmationLetterPDF(employee);
    case "increment-letter": return generateIncrementLetterPDF(employee);
    case "promotion-letter": return generatePromotionLetterPDF(employee);
    case "relieving-letter": return generateRelievingLetterPDF(employee);
  }
}

export function getFilename(employee: Employee, type: DocType) {
  const name = `${employee.firstName}_${employee.lastName}`;
  const labels: Record<DocType, string> = {
    "offer-letter": "Offer_Letter",
    "confirmation-letter": "Confirmation_Letter",
    "increment-letter": "Increment_Letter",
    "promotion-letter": "Promotion_Letter",
    "relieving-letter": "Relieving_Letter",
  };
  return `${labels[type]}_${name}.pdf`;
}
