import { Employee, Notification } from "@/types";

const randomId = () => Math.random().toString(36).substring(2, 10).toUpperCase();

export const mockEmployees: Employee[] = [
  {
    id: "emp-1",
    employeeId: "EMP-001",
    firstName: "Arjun",
    lastName: "Sharma",
    dateOfBirth: "1992-04-15",
    gender: "Male",
    maritalStatus: "Married",
    email: "arjun.sharma@email.com",
    mobile: "9876543210",
    alternateNumber: "9876543211",
    emergencyContact: "9876543212",
    currentAddress: "123 MG Road, Bangalore",
    permanentAddress: "45 Gandhi Nagar, Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560001",
    department: "Engineering",
    designation: "Senior Software Engineer",
    joiningDate: "2022-01-10",
    employmentType: "Full-time",
    workLocation: "Bangalore HQ",
    companyEmail: "arjun.sharma@company.com",
    reportingManager: "Priya Nair",
    shiftTiming: "9 AM - 6 PM",
    officeLocation: "Building A, Floor 3",
    bankName: "HDFC Bank",
    accountHolderName: "Arjun Sharma",
    accountNumber: "50100123456789",
    ifscCode: "HDFC0001234",
    branch: "Koramangala",
    qualification: "B.Tech Computer Science",
    university: "IIT Bangalore",
    yearOfPassing: "2014",
    percentage: "8.5 CGPA",
    previousCompany: "TechCorp India",
    jobTitle: "Software Engineer",
    duration: "3 years",
    lastSalary: "75000",
    fatherName: "Rajesh Sharma",
    motherName: "Sunita Sharma",
    nomineeName: "Priya Sharma",
    nomineeRelation: "Wife",
    status: "approved",
    submittedAt: "2024-01-08T10:30:00Z",
    approvedAt: "2024-01-10T14:00:00Z",
    formLink: `form-${randomId()}`,
    formLinkActive: false,
  },
  {
    id: "emp-2",
    employeeId: "EMP-002",
    firstName: "Priya",
    lastName: "Nair",
    dateOfBirth: "1990-08-22",
    gender: "Female",
    maritalStatus: "Single",
    email: "priya.nair@email.com",
    mobile: "9823456789",
    currentAddress: "67 Anna Nagar, Chennai",
    permanentAddress: "67 Anna Nagar, Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600040",
    department: "HR",
    designation: "HR Manager",
    joiningDate: "2021-06-01",
    employmentType: "Full-time",
    workLocation: "Chennai Office",
    companyEmail: "priya.nair@company.com",
    reportingManager: "Vikram Mehta",
    shiftTiming: "9 AM - 6 PM",
    officeLocation: "Building B, Floor 1",
    bankName: "SBI",
    accountHolderName: "Priya Nair",
    accountNumber: "30456789012345",
    ifscCode: "SBIN0002345",
    branch: "Anna Nagar",
    qualification: "MBA Human Resources",
    university: "Madras University",
    yearOfPassing: "2012",
    percentage: "78%",
    status: "approved",
    submittedAt: "2024-01-05T09:00:00Z",
    approvedAt: "2024-01-07T11:00:00Z",
    formLink: `form-${randomId()}`,
    formLinkActive: false,
  },
  {
    id: "emp-3",
    employeeId: "EMP-003",
    firstName: "Rahul",
    lastName: "Gupta",
    dateOfBirth: "1995-12-01",
    gender: "Male",
    maritalStatus: "Single",
    email: "rahul.gupta@email.com",
    mobile: "9712345678",
    currentAddress: "89 Sector 18, Noida",
    permanentAddress: "89 Sector 18, Noida",
    city: "Noida",
    state: "Uttar Pradesh",
    pincode: "201301",
    department: "Finance",
    designation: "Financial Analyst",
    joiningDate: "2023-03-15",
    employmentType: "Full-time",
    workLocation: "Delhi NCR",
    companyEmail: "rahul.gupta@company.com",
    reportingManager: "Arjun Sharma",
    shiftTiming: "10 AM - 7 PM",
    officeLocation: "Building C, Floor 2",
    bankName: "ICICI Bank",
    accountHolderName: "Rahul Gupta",
    accountNumber: "123456789012",
    ifscCode: "ICIC0001234",
    branch: "Sector 18 Noida",
    qualification: "CA",
    university: "ICAI",
    yearOfPassing: "2018",
    percentage: "68%",
    status: "pending",
    submittedAt: "2024-02-15T11:45:00Z",
    formLink: `form-${randomId()}`,
    formLinkActive: true,
  },
  {
    id: "emp-4",
    employeeId: "EMP-004",
    firstName: "Sneha",
    lastName: "Kulkarni",
    dateOfBirth: "1997-03-10",
    gender: "Female",
    maritalStatus: "Single",
    email: "sneha.k@email.com",
    mobile: "9654321098",
    currentAddress: "12 FC Road, Pune",
    permanentAddress: "12 FC Road, Pune",
    city: "Pune",
    state: "Maharashtra",
    pincode: "411005",
    department: "Design",
    designation: "UI/UX Designer",
    joiningDate: "2023-07-01",
    employmentType: "Full-time",
    workLocation: "Pune Office",
    companyEmail: "sneha.k@company.com",
    reportingManager: "Priya Nair",
    shiftTiming: "9 AM - 6 PM",
    officeLocation: "Building A, Floor 2",
    bankName: "Axis Bank",
    accountHolderName: "Sneha Kulkarni",
    accountNumber: "9876012345678",
    ifscCode: "UTIB0001234",
    branch: "FC Road Pune",
    qualification: "B.Design",
    university: "NID Ahmedabad",
    yearOfPassing: "2019",
    percentage: "9.1 CGPA",
    status: "rejected",
    submittedAt: "2024-02-10T08:30:00Z",
    rejectedAt: "2024-02-12T16:00:00Z",
    rejectionReason: "Incomplete document submission",
    formLink: `form-${randomId()}`,
    formLinkActive: false,
  },
  {
    id: "emp-5",
    employeeId: "EMP-005",
    firstName: "Vikram",
    lastName: "Mehta",
    dateOfBirth: "1985-07-25",
    gender: "Male",
    maritalStatus: "Married",
    email: "vikram.mehta@email.com",
    mobile: "9500123456",
    currentAddress: "34 Juhu, Mumbai",
    permanentAddress: "34 Juhu, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400049",
    department: "Operations",
    designation: "Operations Director",
    joiningDate: "2020-01-01",
    employmentType: "Full-time",
    workLocation: "Mumbai HQ",
    companyEmail: "vikram.mehta@company.com",
    reportingManager: "CEO",
    shiftTiming: "9 AM - 6 PM",
    officeLocation: "Building D, Floor 5",
    bankName: "HDFC Bank",
    accountHolderName: "Vikram Mehta",
    accountNumber: "50200987654321",
    ifscCode: "HDFC0005678",
    branch: "Juhu Mumbai",
    qualification: "MBA Operations",
    university: "IIM Ahmedabad",
    yearOfPassing: "2008",
    percentage: "9.0 CGPA",
    status: "approved",
    submittedAt: "2024-01-01T08:00:00Z",
    approvedAt: "2024-01-03T10:00:00Z",
    formLink: `form-${randomId()}`,
    formLinkActive: false,
  },
  {
    id: "emp-6",
    employeeId: "EMP-006",
    firstName: "Ananya",
    lastName: "Patel",
    dateOfBirth: "1999-02-14",
    gender: "Female",
    maritalStatus: "Single",
    email: "ananya.patel@email.com",
    mobile: "9988776655",
    currentAddress: "56 CG Road, Ahmedabad",
    permanentAddress: "56 CG Road, Ahmedabad",
    city: "Ahmedabad",
    state: "Gujarat",
    pincode: "380009",
    department: "Marketing",
    designation: "Marketing Executive",
    joiningDate: "2023-11-01",
    employmentType: "Full-time",
    workLocation: "Ahmedabad Office",
    companyEmail: "ananya.patel@company.com",
    reportingManager: "Vikram Mehta",
    shiftTiming: "9 AM - 6 PM",
    officeLocation: "Building E, Floor 1",
    bankName: "Kotak Mahindra Bank",
    accountHolderName: "Ananya Patel",
    accountNumber: "1234567890123",
    ifscCode: "KKBK0001234",
    branch: "CG Road Ahmedabad",
    qualification: "BBA Marketing",
    university: "Gujarat University",
    yearOfPassing: "2021",
    percentage: "72%",
    status: "resubmitted",
    submittedAt: "2024-02-18T13:00:00Z",
    formLink: `form-${randomId()}`,
    formLinkActive: true,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    type: "submission",
    title: "New Form Submitted",
    message: "Rahul Gupta has submitted their employee form.",
    employeeId: "emp-3",
    employeeName: "Rahul Gupta",
    read: false,
    createdAt: "2024-02-15T11:45:00Z",
  },
  {
    id: "notif-2",
    type: "resubmitted",
    title: "Form Re-Submitted",
    message: "Ananya Patel has re-submitted their employee form.",
    employeeId: "emp-6",
    employeeName: "Ananya Patel",
    read: false,
    createdAt: "2024-02-18T13:00:00Z",
  },
  {
    id: "notif-3",
    type: "approved",
    title: "Employee Approved",
    message: "Arjun Sharma has been approved successfully.",
    employeeId: "emp-1",
    employeeName: "Arjun Sharma",
    read: true,
    createdAt: "2024-01-10T14:00:00Z",
  },
  {
    id: "notif-4",
    type: "rejected",
    title: "Form Rejected",
    message: "Sneha Kulkarni's form was rejected due to incomplete documents.",
    employeeId: "emp-4",
    employeeName: "Sneha Kulkarni",
    read: true,
    createdAt: "2024-02-12T16:00:00Z",
  },
];
